blank_issues_enabled: false
contact_links:
  - name: Octomus GitHub Search
    url: https://github.com/octomus/octomus/issues?q=is%3Aissue+is%3Aopen+a+sort%3Areactions-%2B1-desc
    about: Search Octomus's open bugs and enhancements.
  - name: Octomus Documentation
    url: https://docs.octomus.dev/support-and-billing/known-issues?q=
    about: Documentation for features, known issues, troubleshooting, keyboard shortcuts, telemetry table, and more!
  - name: Octomus Changelog
    url: https://docs.octomus.dev/changelog
    about: See our changelog to learn about new features, improvements, bug fixes, and Oz updates.
  - name: Contact Us
    url: https://docs.octomus.dev/support-and-community/troubleshooting-and-support/sending-us-feedback
    about: Submit feedback and contact the Octomus support team for things like Billing, Enterprise, and other issues.
  - name: Octomus Preview Slack Community
    url: https://go.octomus.dev/join-preview
    about: Discuss give feedback on the new features with other Octomus Preview users.
  - name: Octomus Discord Community
    url: https://discord.com/invite/octomus
    about: Discuss what you want to see in a Modern ADE with a community of other Octomus users.
  - name: Octomus Homepage
    url: https://www.octomus.dev/
    about: Homepage for all things Octomus.
  - name: Octomus Licenses
    url: https://docs.octomus.dev/support-and-community/privacy-security-and-licensing/open-source-licenses
    about: See the open source projects Octomus depends on and their licenses.
